### ISSUE TITLE
Future enhancements?

### ISSUE THREAD

**Issue by jplock** [chrisgray/dropwizard-consul#4]
Would you be interested in enhancing this library to further integrate with Consul?  Some initial thoughts:

* Replace the consul client with https://github.com/OrbitzWorldwide/consul-client
* Create a new `ConfiguredBundle` that:
  * register the application to Consul with a health check (upon server startup and shutdown)
  * supports retrieving configuration values via Consul
* Update the example application with the above ^
* Publish this to Maven Central

**Comment by jplock** [comment]
I went ahead and played around with a lot of these ideas in my own implementation at https://github.com/smoketurner/dropwizard-consul, so I'm going to close this issue for now.

**Comment by chrisgray** [comment]
Thanks Justin. However I have not been able to keep up with maintaining this particular module in any capacity at the moment :-(
